services:
  inference:
    build: 
        context: .
        dockerfile: serving/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - REDIS_HOST=redis

    depends_on:
      mlflow:
        condition: service_healthy
      redis:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
        - inference
    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
        - "3000:3000"
    volumes:
        - grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
        - prometheus
  mlflow:
    image: python:3.10-slim
    working_dir: /mlflow
    environment:
      - MLFLOW_SERVER_ALLOWED_HOSTS=mlflow,mlflow:5000,localhost,localhost:5000,127.0.0.1,127.0.0.1:5000
    volumes:
      - ./mlflow.db:/mlflow/mlflow.db
      - ./mlartifacts:/mlflow/mlartifacts
    command: >-
        bash -c "pip install mlflow && pip install flask && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlartifacts"
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server

volumes:
  grafana_data: